<a href="https://colab.research.google.com/github/yawarabbasmalik/Diabetes-Prediction/blob/main/Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing necessary libraries for dataset loading

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

In [ ]:
#importing the data file

df = pd.read_csv("diabetes.csv", index_col=False)
df

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
scaleIt = MinMaxScaler()
columns_to_be_scaled = [c for c in df.columns if df[c].max() > 1]
print("The columns which are to be scaled are :",columns_to_be_scaled)

scaled_columns = scaleIt.fit_transform(df[columns_to_be_scaled])
scaled_columns = pd.DataFrame(scaled_columns, columns=columns_to_be_scaled)
scaled_columns['Outcome'] = df['Outcome']

The columns which are to be scaled are : ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

In [ ]:
df=scaled_columns
df

     Pregnancies   Glucose  ...       Age  Outcome
0       0.352941  0.743719  ...  0.483333        1
1       0.058824  0.427136  ...  0.166667        0
2       0.470588  0.919598  ...  0.183333        1
3       0.058824  0.447236  ...  0.000000        0
4       0.000000  0.688442  ...  0.200000        1
..           ...       ...  ...       ...      ...
763     0.588235  0.507538  ...  0.700000        0
764     0.117647  0.613065  ...  0.100000        0
765     0.294118  0.608040  ...  0.150000        0
766     0.058824  0.633166  ...  0.433333        1
767     0.058824  0.467337  ...  0.033333        0

[768 rows x 9 columns]

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1:]
x.head(10),y.head(10)

(   Pregnancies   Glucose  ...  DiabetesPedigreeFunction       Age
 0     0.352941  0.743719  ...                  0.234415  0.483333
 1     0.058824  0.427136  ...                  0.116567  0.166667
 2     0.470588  0.919598  ...                  0.253629  0.183333
 3     0.058824  0.447236  ...                  0.038002  0.000000
 4     0.000000  0.688442  ...                  0.943638  0.200000
 5     0.294118  0.582915  ...                  0.052519  0.150000
 6     0.176471  0.391960  ...                  0.072588  0.083333
 7     0.588235  0.577889  ...                  0.023911  0.133333
 8     0.117647  0.989950  ...                  0.034159  0.533333
 9     0.470588  0.628141  ...                  0.065756  0.550000

 [10 rows x 8 columns],    Outcome
 0        1
 1        0
 2        1
 3        0
 4        1
 5        0
 6        1
 7        0
 8        1
 9        1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y , test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

In [ ]:
# building Naive Bayes Model for diabetes patients
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(x_train, y_train)

predicted = model.predict(x_test)

print ("The accuracy of Gaussian Naive Bayes is : ", accuracy_score(y_test, predicted)*100, "%")
print()
print("Precision score for Gaussian Naive Bayes is :",precision_score(y_test, predicted,)*100, "%")
print()
print("Recall score for Gaussian Naive Bayes is :",recall_score(y_test, predicted,)*100, "%")

The accuracy of Gaussian Naive Bayes is :  76.62337662337663 %

Precision score for Gaussian Naive Bayes is : 66.10169491525424 %

Recall score for Gaussian Naive Bayes is : 70.9090909090909 %

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
# building SVM Model for diabetes patients
from sklearn.svm import SVC

model = SVC()
model.fit(x_train, y_train)
predicted = model.predict(x_test)

print ("The accuracy of SVM is : ", accuracy_score(y_test, predicted)*100, "%")
print()
print("Precision score for SVM is :",precision_score(y_test, predicted,)*100, "%")
print()
print("Recall score for SVM is :",recall_score(y_test, predicted,)*100, "%")

The accuracy of SVM is :  74.67532467532467 %

Precision score for SVM is : 66.0 %

Recall score for SVM is : 60.0 %

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:

# building Decision Tree for diabetes patients
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)
predicted = model.predict(x_test)

print ("The accuracy of Decision Tree is : ", accuracy_score(y_test, predicted)*100, "%")
print()
print("Precision score for Decision Tree is :",precision_score(y_test, predicted,)*100, "%")
print()
print("Recall score for Decision Tree is :",recall_score(y_test, predicted,)*100, "%")

The accuracy of Decision Tree is :  74.67532467532467 %

Precision score for Decision Tree is : 63.793103448275865 %

Recall score for Decision Tree is : 67.27272727272727 %